In [1]:
from fastai.tabular.all import *

In [2]:
path = Path('../../data/kaggle-wine/')

In [3]:
df = pd.read_csv(path/'winequality-red.csv')

In [4]:
df.loc[:,'quality'].unique(), df.columns

(array([5, 6, 7, 4, 8, 3]),
 Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
        'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
        'pH', 'sulphates', 'alcohol', 'quality'],
       dtype='object'))

In [5]:
cont_names = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
        'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
        'pH', 'sulphates', 'alcohol']

In [6]:
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
splits = RandomSplitter(valid_pct=0.2)(range_of(df))

In [8]:
dep_var = 'quality'

In [9]:
to = TabularPandas(df, procs=[Categorify, FillMissing,Normalize],
                   cont_names = cont_names,
                   y_names=dep_var,
                   splits=splits,y_block = CategoryBlock())

In [17]:
dls = to.dataloaders(bs=32)

In [18]:
dls.show_batch()

In [19]:
learn = tabular_learner(dls, metrics=accuracy)

In [20]:
learn.fit_one_cycle(10)

learn.show_results()